BANCO = {
    "manguito_rotador": {
        "nombre": "Manguito Rotador", "nivel": 1, "categoria": "Miembro Superior",
        "preguntas": [
            {"id":"mr_001","concepto":"músculos SITS","enunciado":"¿Cuál de los siguientes NO forma parte del manguito rotador?","opciones":{"A":"Supraespinoso","B":"Infraespinoso","C":"Deltoides","D":"Subescapular"},"correcta":"C","exp":"El manguito rotador = SITS: Supraespinoso, Infraespinoso, Teres minor, Subescapular. El deltoides es extrínseco y no forma parte."},
            {"id":"mr_002","concepto":"músculos SITS","enunciado":"La nemotecnia SITS del manguito rotador corresponde a:","opciones":{"A":"Supraespinoso, Infraespinoso, Teres minor, Subescapular","B":"Subescapular, Infraespinoso, Teres major, Supraespinoso","C":"Supraespinoso, Infraespinoso, Trapecio, Subescapular","D":"Supraespinoso, Iliocostal, Teres minor, Subescapular"},"correcta":"A","exp":"SITS: Supraespinoso (abducción), Infraespinoso (rot. externa), Teres minor (rot. externa), Subescapular (rot. interna). Los 4 estabilizan la cabeza humeral."},
            {"id":"mr_003","concepto":"función supraespinoso","enunciado":"El músculo supraespinoso es el principal responsable de:","opciones":{"A":"Rotación externa del hombro","B":"Inicio de la abducción (0-15°)","C":"Rotación interna del hombro","D":"Aducción del brazo"},"correcta":"B","exp":"El supraespinoso inicia la abducción del hombro en los primeros 0-15°. A partir de 15°, el deltoides toma el relevo. Es el músculo del manguito más frecuentemente lesionado."},
            {"id":"mr_004","concepto":"músculo más lesionado","enunciado":"¿Cuál es el músculo del manguito rotador más frecuentemente lesionado?","opciones":{"A":"Infraespinoso","B":"Teres minor","C":"Supraespinoso","D":"Subescapular"},"correcta":"C","exp":"El supraespinoso es el más lesionado por su paso bajo el arco coracoacromial, donde queda atrapado en la abducción (síndrome de atrapamiento subacromial)."},
            {"id":"mr_005","concepto":"rotación interna","enunciado":"¿Qué músculo del manguito rotador realiza rotación INTERNA del hombro?","opciones":{"A":"Supraespinoso","B":"Infraespinoso","C":"Teres minor","D":"Subescapular"},"correcta":"D","exp":"El subescapular es el único del manguito que hace rotación interna. Se origina en la fosa subescapular de la escápula e inserta en el troquín (tubérculo menor)."},
            {"id":"mr_006","concepto":"inervación","enunciado":"¿Qué nervio inerva el supraespinoso y el infraespinoso?","opciones":{"A":"Nervio axilar","B":"Nervio supraescapular","C":"Nervio subescapular","D":"Nervio musculocutáneo"},"correcta":"B","exp":"El nervio supraescapular (C5-C6) inerva supraespinoso e infraespinoso. El nervio axilar inerva el deltoides y teres minor. El nervio subescapular inerva el subescapular."},
            {"id":"mr_007","concepto":"inervación","enunciado":"El músculo subescapular está inervado por el nervio:","opciones":{"A":"Supraescapular","B":"Axilar","C":"Subescapular superior e inferior","D":"Toracodorsal"},"correcta":"C","exp":"El subescapular está inervado por los nervios subescapulares superior e inferior (ramas del fascículo posterior, C5-C6). No confundir con el nervio supraescapular que inerva supraespinoso e infraespinoso."},
            {"id":"mr_008","concepto":"test clínico","enunciado":"El test de Jobe (empty can test) explora la integridad del:","opciones":{"A":"Infraespinoso","B":"Subescapular","C":"Supraespinoso","D":"Teres minor"},"correcta":"C","exp":"El test de Jobe: hombro abducido 90°, anteversión 30°, rotación interna (pulgar hacia abajo). Se aplica resistencia. Dolor o debilidad = lesión del supraespinoso."},
            {"id":"mr_009","concepto":"rotación externa","enunciado":"Los músculos del manguito que realizan rotación EXTERNA del hombro son:","opciones":{"A":"Supraespinoso y subescapular","B":"Infraespinoso y teres minor","C":"Subescapular y teres minor","D":"Supraespinoso e infraespinoso"},"correcta":"B","exp":"Infraespinoso y teres minor son los rotadores externos del manguito. Ambos se insertan en el troquíter (tubérculo mayor). El infraespinoso es el más potente de los dos."},
            {"id":"mr_010","concepto":"arco coracoacromial","enunciado":"¿Por qué espacio pasa el tendón del supraespinoso?","opciones":{"A":"Canal carpiano","B":"Bajo el arco coracoacromial","C":"Por el canal de Guyon","D":"Sobre el ligamento acromioclavicular"},"correcta":"B","exp":"El tendón del supraespinoso pasa por el espacio subacromial, bajo el arco coracoacromial (acromion + ligamento coracoacromial + apófisis coracoides). La reducción de este espacio causa el síndrome de atrapamiento."},
        ]
    },
    "plexo_braquial": {
        "nombre": "Plexo Braquial", "nivel": 1, "categoria": "Miembro Superior",
        "preguntas": [
            {"id":"pb_001","concepto":"raíces","enunciado":"¿Cuáles son las raíces del plexo braquial?","opciones":{"A":"C4-C5-C6-C7-C8","B":"C5-C6-C7-C8-T1","C":"C4-C5-C6-C7-T1","D":"C5-C6-C7-T1-T2"},"correcta":"B","exp":"El plexo braquial se forma por las ramas anteriores de C5, C6, C7, C8 y T1. Existe variante prefijada (C4-C8) y posfijada (C6-T2), pero la estándar es C5-T1."},
            {"id":"pb_002","concepto":"troncos","enunciado":"¿Cuántos troncos tiene el plexo braquial y cómo se llaman?","opciones":{"A":"2 troncos: superior e inferior","B":"3 troncos: superior, medio e inferior","C":"4 troncos: lateral, medial, posterior y anterior","D":"3 troncos: anterior, medio y posterior"},"correcta":"B","exp":"El plexo tiene 3 troncos: Superior (C5-C6), Medio (C7) e Inferior (C8-T1). Los troncos se dividen en divisiones anteriores y posteriores que forman los fascículos."},
            {"id":"pb_003","concepto":"troncos","enunciado":"El tronco superior del plexo braquial está formado por las raíces:","opciones":{"A":"C5 solo","B":"C5 y C6","C":"C6 y C7","D":"C5, C6 y C7"},"correcta":"B","exp":"Tronco superior = C5 + C6. Tronco medio = C7 (solo). Tronco inferior = C8 + T1. La lesión del tronco superior da la parálisis de Erb-Duchenne."},
            {"id":"pb_004","concepto":"fascículos","enunciado":"¿Cuántos fascículos tiene el plexo braquial?","opciones":{"A":"3 fascículos: lateral, medial y posterior","B":"4 fascículos: anterior, posterior, medial y lateral","C":"2 fascículos: medial y lateral","D":"3 fascículos: superior, medio e inferior"},"correcta":"A","exp":"Los 3 fascículos se nombran por su relación con la arteria axilar: Lateral (divisiones anteriores de troncos sup. y medio), Medial (división anterior del tronco inf.) y Posterior (todas las divisiones posteriores)."},
            {"id":"pb_005","concepto":"parálisis Erb","enunciado":"La parálisis de Erb-Duchenne afecta las raíces:","opciones":{"A":"C8-T1","B":"C5-C6","C":"C7-C8","D":"C5-C6-C7"},"correcta":"B","exp":"Erb-Duchenne = C5-C6 (tronco superior). Causa: tracción forzada del hombro hacia abajo (parto, accidente). Posición típica: 'brazo de camarero': aducción, rotación interna y pronación del antebrazo."},
            {"id":"pb_006","concepto":"parálisis Klumpke","enunciado":"La parálisis de Klumpke afecta las raíces:","opciones":{"A":"C5-C6","B":"C6-C7","C":"C8-T1","D":"C7-C8-T1"},"correcta":"C","exp":"Klumpke = C8-T1 (tronco inferior). Causa: tracción del brazo hacia arriba (parto podálico, colgar del brazo). Produce 'mano en garra' por parálisis de los intrínsecos. Si afecta T1 → síndrome de Horner (ptosis, miosis, anhidrosis)."},
            {"id":"pb_007","concepto":"nervio mediano","enunciado":"¿De qué fascículos proviene el nervio mediano?","opciones":{"A":"Solo del fascículo lateral","B":"Solo del fascículo medial","C":"De los fascículos lateral y medial","D":"Del fascículo posterior"},"correcta":"C","exp":"El nervio mediano tiene dos raíces: una del fascículo lateral (C5-C7) y otra del fascículo medial (C8-T1). Forman la letra M sobre la arteria axilar. Es el único nervio con dos raíces de fascículos diferentes."},
            {"id":"pb_008","concepto":"nervio radial","enunciado":"¿De qué fascículo proviene el nervio radial?","opciones":{"A":"Fascículo lateral","B":"Fascículo medial","C":"Fascículo posterior","D":"Tronco superior directamente"},"correcta":"C","exp":"El nervio radial proviene del fascículo posterior (junto con el axilar). Inerva todos los extensores del brazo y antebrazo. Pasa por el surco de torsión del húmero. Su lesión produce 'mano caída' (wrist drop)."},
            {"id":"pb_009","concepto":"nervio cubital","enunciado":"La lesión del nervio cubital en el codo produce:","opciones":{"A":"Mano caída (wrist drop)","B":"Mano de predicador","C":"Mano en garra (4º y 5º dedos)","D":"Pérdida de flexión del codo"},"correcta":"C","exp":"El nervio cubital (ulnar, del fascículo medial) lesionado en el codo produce garra de los dedos anular y meñique (4º-5º) porque los lumbricales de esos dedos quedan paralizados. La lesión alta en axila da garra de todos los dedos."},
            {"id":"pb_010","concepto":"nervio musculocutáneo","enunciado":"¿Qué inerva el nervio musculocutáneo?","opciones":{"A":"Músculos extensores del codo","B":"Músculos flexores del brazo y piel de antebrazo lateral","C":"Músculos intrínsecos de la mano","D":"Músculo deltoides y teres minor"},"correcta":"B","exp":"El nervio musculocutáneo (del fascículo lateral, C5-C7) inerva: bíceps, braquial anterior y coracobraquial. Continúa como nervio cutáneo lateral del antebrazo (sensitivo). Su lesión es rara aislada."},
        ]
    },
    "huesos_ms": {
        "nombre": "Huesos Miembro Superior", "nivel": 1, "categoria": "Miembro Superior",
        "preguntas": [
            {"id":"hms_001","concepto":"anatomía húmero","enunciado":"¿En qué zona del húmero se inserta el músculo deltoides?","opciones":{"A":"Troquíter (tubérculo mayor)","B":"Troquín (tubérculo menor)","C":"Tuberosidad deltoidea (cara lateral)","D":"Epicóndilo lateral"},"correcta":"C","exp":"El deltoides se inserta en la tuberosidad deltoidea, una rugosidad en la cara anterolateral del cuerpo del húmero, aproximadamente a mitad del hueso."},
            {"id":"hms_002","concepto":"anatomía húmero","enunciado":"¿Qué estructura pasa por el surco bicipital (corredera bicipital) del húmero?","opciones":{"A":"Nervio radial","B":"Tendón de la cabeza larga del bíceps","C":"Arteria axilar","D":"Nervio musculocutáneo"},"correcta":"B","exp":"La corredera bicipital (surco intertubercular) es un canal entre el troquíter y el troquín por donde discurre el tendón de la cabeza larga del bíceps braquial."},
            {"id":"hms_003","concepto":"nervio en surco","enunciado":"El nervio radial discurre por:","opciones":{"A":"Canal carpiano","B":"Surco de torsión (espiral) del húmero","C":"Corredera bicipital","D":"Canal de Guyon"},"correcta":"B","exp":"El nervio radial pasa por el surco de torsión (espiral) en la cara posterior del húmero. Por eso, las fracturas de diáfisis humeral pueden lesionar el nervio radial, produciendo mano caída."},
            {"id":"hms_004","concepto":"anatomía cúbito","enunciado":"El olécranon es una estructura del:","opciones":{"A":"Radio","B":"Húmero","C":"Cúbito","D":"Escafoides"},"correcta":"C","exp":"El olécranon es la prominencia posterior del cúbito que forma el 'codo'. Es la inserción del tríceps braquial. El proceso coronoides del cúbito es la parte anterior que cabe en la fosa coronoidea del húmero."},
            {"id":"hms_005","concepto":"carpo proximal","enunciado":"Los huesos del carpo en la fila PROXIMAL de radial a cubital son:","opciones":{"A":"Trapecio, Trapezoide, Grande, Ganchoso","B":"Escafoides, Semilunar, Piramidal, Pisiforme","C":"Pisiforme, Piramidal, Semilunar, Escafoides","D":"Escafoides, Grande, Piramidal, Pisiforme"},"correcta":"B","exp":"Fila proximal (de radial a cubital): Escafoides - Semilunar - Piramidal - Pisiforme. Fila distal: Trapecio - Trapezoide - Grande - Ganchoso. Nemotecnia: 'El Sábado Por la Tarde Tomamos Gin con Hielo'."},
            {"id":"hms_006","concepto":"carpo distal","enunciado":"Los huesos del carpo en la fila DISTAL de radial a cubital son:","opciones":{"A":"Escafoides, Semilunar, Piramidal, Pisiforme","B":"Grande, Ganchoso, Trapecio, Trapezoide","C":"Trapecio, Trapezoide, Grande, Ganchoso","D":"Trapecio, Grande, Trapezoide, Ganchoso"},"correcta":"C","exp":"Fila distal (de radial a cubital): Trapecio - Trapezoide - Grande - Ganchoso. El Trapecio articula con el 1er metacarpiano (pulgar). El Ganchoso tiene el gancho que se puede palpar en la palma."},
            {"id":"hms_007","concepto":"hueso más fracturado carpo","enunciado":"¿Cuál es el hueso del carpo más frecuentemente fracturado?","opciones":{"A":"Pisiforme","B":"Grande","C":"Escafoides","D":"Semilunar"},"correcta":"C","exp":"El escafoides es el hueso del carpo más frecuentemente fracturado (70% de fracturas del carpo). Ocurre por caída sobre la mano en extensión. El dolor en la tabaquera anatómica es su signo clásico. Riesgo de necrosis avascular."},
            {"id":"hms_008","concepto":"acromion","enunciado":"El acromion es una estructura de:","opciones":{"A":"Clavícula","B":"Húmero","C":"Escápula","D":"Primera costilla"},"correcta":"C","exp":"El acromion es la prolongación lateral de la espina de la escápula. Forma el techo de la articulación del hombro y el arco coracoacromial junto con el ligamento coracoacromial y la apófisis coracoides."},
            {"id":"hms_009","concepto":"articulación radiocubital","enunciado":"La pronosupinación del antebrazo ocurre en las articulaciones:","opciones":{"A":"Del codo únicamente","B":"Radiocubitales proximal y distal","C":"De la muñeca únicamente","D":"Radiocarpiana y mediocarpiana"},"correcta":"B","exp":"La pronosupinación ocurre en las articulaciones radiocubitales proximal (trocoidea, en el codo) y distal (trocoidea, en la muñeca). El radio rota alrededor del cúbito, que es el eje fijo."},
            {"id":"hms_010","concepto":"fractura colles","enunciado":"La fractura de Colles es una fractura de:","opciones":{"A":"Escafoides por caída sobre mano","B":"Extremo distal del radio con desplazamiento dorsal","C":"Diáfisis del cúbito","D":"Cabeza del radio"},"correcta":"B","exp":"La fractura de Colles es una fractura del extremo distal del radio con desplazamiento dorsal del fragmento distal ('deformidad en dorso de tenedor'). Ocurre por caída sobre la mano extendida. Es la fractura más común en adultos mayores."},
        ]
    },
    "huesos_mi": {
        "nombre": "Huesos Miembro Inferior", "nivel": 1, "categoria": "Miembro Inferior",
        "preguntas": [
            {"id":"hmi_001","concepto":"fémur","enunciado":"¿Cuál es el hueso más largo del cuerpo humano?","opciones":{"A":"Tibia","B":"Fémur","C":"Húmero","D":"Peroné"},"correcta":"B","exp":"El fémur es el hueso más largo y resistente del cuerpo. Forma la articulación de la cadera (con el acetábulo) y de la rodilla (con la tibia y la rótula)."},
            {"id":"hmi_002","concepto":"trocánteres","enunciado":"El trocánter MAYOR del fémur es inserción principalmente de:","opciones":{"A":"Iliopsoas","B":"Glúteo mayor","C":"Glúteos medio y menor","D":"Cuádriceps femoral"},"correcta":"C","exp":"El trocánter mayor es la inserción de los glúteos medio y menor (abductores). El trocánter menor es la inserción del iliopsoas (flexor de cadera). El glúteo mayor se inserta en la tuberosidad glútea del fémur."},
            {"id":"hmi_003","concepto":"rótula","enunciado":"La rótula es un hueso de tipo:","opciones":{"A":"Largo","B":"Corto","C":"Sesamoideo","D":"Irregular"},"correcta":"C","exp":"La rótula es el hueso sesamoideo más grande del cuerpo. Está incluida en el tendón del cuádriceps femoral. Aumenta el brazo de palanca del cuádriceps para la extensión de la rodilla."},
            {"id":"hmi_004","concepto":"maléolos","enunciado":"El maléolo MEDIAL (interno) es una estructura de:","opciones":{"A":"Peroné","B":"Tibia","C":"Fémur","D":"Astrágalo"},"correcta":"B","exp":"El maléolo medial es la prominencia distal medial de la tibia. El maléolo lateral (externo) es la parte distal del peroné. Juntos forman la mortaja tibioperonea que abraza al astrágalo."},
            {"id":"hmi_005","concepto":"tarso","enunciado":"¿Cuántos huesos tiene el tarso?","opciones":{"A":"5","B":"6","C":"7","D":"8"},"correcta":"C","exp":"El tarso tiene 7 huesos: Calcáneo, Astrágalo, Navicular, Cuboides y 3 Cuneiformes (medial, intermedio, lateral). Nemotecnia: 'Ca-As-Na-Cu-3C'."},
            {"id":"hmi_006","concepto":"calcáneo","enunciado":"¿Cuál es el hueso más grande del tarso?","opciones":{"A":"Astrágalo","B":"Navicular","C":"Calcáneo","D":"Cuboides"},"correcta":"C","exp":"El calcáneo es el mayor del tarso y forma el talón. Es la inserción del tendón de Aquiles (tríceps sural). La fractura del calcáneo es la fractura de tarso más frecuente (caídas desde altura)."},
            {"id":"hmi_007","concepto":"astrágalo","enunciado":"¿Qué hueso del tarso articula directamente con la tibia?","opciones":{"A":"Calcáneo","B":"Navicular","C":"Astrágalo","D":"Cuboides"},"correcta":"C","exp":"El astrágalo articula con tibia y peroné (mortaja tibioperonea) formando la articulación del tobillo (articulación talocrural). Es el único hueso del tarso sin inserción muscular directa."},
            {"id":"hmi_008","concepto":"pie en total","enunciado":"¿Cuántos huesos tiene el pie en total?","opciones":{"A":"24","B":"26","C":"28","D":"30"},"correcta":"B","exp":"El pie tiene 26 huesos: 7 tarsianos + 5 metatarsianos + 14 falanges (2 en el 1er dedo y 3 en el resto). Igual que la mano (27 con el sesamoideo del pulgar)."},
            {"id":"hmi_009","concepto":"fractura cadera","enunciado":"En fracturas de cuello femoral, ¿qué arteria está en riesgo de lesión?","opciones":{"A":"Arteria femoral","B":"Arterias circunflejas femorales","C":"Arteria poplítea","D":"Arteria obturatriz"},"correcta":"B","exp":"Las arterias circunflejas femorales medial y lateral irrigan la cabeza y cuello del fémur. Su lesión en fracturas de cuello femoral puede causar necrosis avascular de la cabeza femoral. Por eso es una fractura de urgencia."},
            {"id":"hmi_010","concepto":"línea intertrocantérea","enunciado":"¿Dónde se origina el ligamento iliofemoral (ligamento de Bigelow)?","opciones":{"A":"En la espina ilíaca anterosuperior","B":"En la espina ilíaca anteroinferior y línea intertrocantérea","C":"En el trocánter mayor","D":"En el acetábulo"},"correcta":"B","exp":"El ligamento iliofemoral (de Bigelow) es el más fuerte del cuerpo. Une la espina ilíaca anteroinferior con la línea intertrocantérea. Tiene forma de Y y previene la hiperextensión de la cadera."},
        ]
    },
    "nervios_mmii": {
        "nombre": "Nervios Miembro Inferior", "nivel": 1, "categoria": "Miembro Inferior",
        "preguntas": [
            {"id":"nmi_001","concepto":"nervio ciático","enunciado":"¿De qué raíces se origina el nervio ciático?","opciones":{"A":"L2-L3-L4","B":"L3-L4-L5-S1","C":"L4-L5-S1-S2-S3","D":"L2-L3-L4-L5"},"correcta":"C","exp":"El nervio ciático (plexo sacro) se origina de L4-L5-S1-S2-S3. Es el nervio más largo y grueso del cuerpo. Sale por el foramen ciático mayor, pasa bajo el piriforme y desciende por la cara posterior del muslo."},
            {"id":"nmi_002","concepto":"nervio ciático","enunciado":"¿Dónde se divide el nervio ciático en sus dos ramas terminales?","opciones":{"A":"Glúteo mayor","B":"Canal de Hunter","C":"Fosa poplítea","D":"Foramen ciático menor"},"correcta":"C","exp":"El nervio ciático se divide en la fosa poplítea (vértice superior) en: nervio tibial (continúa hacia abajo) y nervio peroneo común (rodea la cabeza del peroné). Esta división puede ocurrir más arriba en variantes anatómicas."},
            {"id":"nmi_003","concepto":"nervio peroneo","enunciado":"La lesión del nervio peroneo común en el cuello del peroné produce:","opciones":{"A":"Pie equino (flexión plantar fija)","B":"Pie caído (steppage) por parálisis de dorsiflexores","C":"Pérdida de flexión de rodilla","D":"Parálisis de los aductores"},"correcta":"B","exp":"El nervio peroneo común rodea el cuello del peroné y es muy vulnerable. Su lesión paraliza el tibial anterior (dorsiflexión) y extensores de los dedos → 'pie caído'. El paciente levanta exageradamente la rodilla al caminar (marcha en steppage)."},
            {"id":"nmi_004","concepto":"nervio femoral","enunciado":"¿Qué inerva el nervio femoral?","opciones":{"A":"Músculos aductores del muslo","B":"Cuádriceps femoral y sensibilidad anterior del muslo","C":"Flexores del muslo","D":"Músculos de la pierna"},"correcta":"B","exp":"El nervio femoral (L2-L4) inerva: cuádriceps (extensión de rodilla), sartorio, pectíneo, y la sensibilidad de la cara anterior del muslo y parte medial de la pierna (nervio safeno). Su lesión imposibilita extender la rodilla."},
            {"id":"nmi_005","concepto":"nervio obturador","enunciado":"¿Qué músculos inerva el nervio obturador?","opciones":{"A":"Extensores del muslo","B":"Aductores del muslo","C":"Flexores de la rodilla","D":"Dorsiflexores del pie"},"correcta":"B","exp":"El nervio obturador (L2-L4) inerva los aductores del muslo: pectíneo, aductor largo, corto y mayor, grácil y obturador externo. Sale por el agujero obturador. Su lesión: dificultad para cruzar las piernas."},
            {"id":"nmi_006","concepto":"nervio tibial","enunciado":"¿Qué produce la lesión del nervio tibial?","opciones":{"A":"Pie caído","B":"Pie zambo (equinovaro) y pérdida de flexión plantar","C":"Pérdida de extensión de la rodilla","D":"Parálisis del glúteo"},"correcta":"B","exp":"El nervio tibial (L4-S3) inerva los flexores plantares (tríceps sural) y los músculos de la planta del pie. Su lesión produce pie en calcáneo (incapacidad para la flexión plantar), pérdida de la sensibilidad plantar."},
            {"id":"nmi_007","concepto":"plexo lumbar","enunciado":"¿Cuál de estos nervios NO pertenece al plexo lumbar?","opciones":{"A":"Nervio femoral","B":"Nervio obturador","C":"Nervio iliohipogástrico","D":"Nervio ciático"},"correcta":"D","exp":"El nervio ciático es la principal rama del plexo SACRO (L4-S3). El plexo lumbar (L1-L4) da: iliohipogástrico, ilioinguinal, genitofemoral, cutáneo lateral del muslo, femoral y obturador."},
            {"id":"nmi_008","concepto":"síndrome del piriforme","enunciado":"El síndrome del piriforme puede comprimir al nervio:","opciones":{"A":"Femoral","B":"Obturador","C":"Ciático","D":"Peroneo superficial"},"correcta":"C","exp":"El nervio ciático pasa bajo el músculo piriforme (o a veces a través de él). La hipertensión/contractura del piriforme puede comprimir el ciático, causando dolor similar a la ciática discal. Se alivia con estiramiento del piriforme."},
            {"id":"nmi_009","concepto":"dermatomas","enunciado":"El dermatoma del dorso del pie (excepto 1er espacio interdigital) corresponde a:","opciones":{"A":"L3","B":"L4","C":"L5","D":"S1"},"correcta":"C","exp":"L5 inerva la parte dorsal del pie y el 1er espacio interdigital (entre 1er y 2er dedo). S1 inerva el talón y el borde lateral del pie. L4 inerva la cara medial de la pierna. Importante para localizar hernias discales."},
            {"id":"nmi_010","concepto":"hernia L5-S1","enunciado":"Una hernia discal L5-S1 que comprime la raíz S1 produce:","opciones":{"A":"Pérdida de reflejo rotuliano","B":"Pérdida de reflejo aquíleo","C":"Pie caído","D":"Debilidad del cuádriceps"},"correcta":"B","exp":"La raíz S1 se evalúa con: reflejo aquíleo (se pierde), sensibilidad del talón y borde lateral del pie, y fuerza de la flexión plantar (puntillas). La raíz L4 da el reflejo rotuliano; L4-L5 da la dorsiflexión del pie."},
        ]
    },
    "rodilla": {
        "nombre": "Rodilla", "nivel": 1, "categoria": "Miembro Inferior",
        "preguntas": [
            {"id":"rod_001","concepto":"LCA","enunciado":"¿Cuál es la función principal del ligamento cruzado anterior (LCA)?","opciones":{"A":"Evitar el desplazamiento posterior de la tibia","B":"Evitar el desplazamiento anterior de la tibia sobre el fémur","C":"Evitar el valgo de rodilla","D":"Evitar la rotación externa de la tibia"},"correcta":"B","exp":"El LCA evita el desplazamiento anterior de la tibia respecto al fémur. Se tensa en extensión de rodilla. Su lesión es la más frecuente en deportes de pivote (fútbol, esquí). El cajón anterior y el test de Lachman lo evalúan."},
            {"id":"rod_002","concepto":"LCA","enunciado":"El test de Lachman valora la integridad del:","opciones":{"A":"Ligamento colateral medial","B":"Menisco medial","C":"Ligamento cruzado anterior","D":"Ligamento cruzado posterior"},"correcta":"C","exp":"El test de Lachman es el gold standard para lesión del LCA: rodilla a 20-30° de flexión, se tracciona la tibia hacia adelante. Positivo: desplazamiento anterior sin tope firme. Más sensible que el cajón anterior en agudo."},
            {"id":"rod_003","concepto":"LCP","enunciado":"La función del ligamento cruzado posterior (LCP) es:","opciones":{"A":"Evitar el desplazamiento anterior de la tibia","B":"Evitar el desplazamiento posterior de la tibia sobre el fémur","C":"Estabilizar el compartimento medial","D":"Guiar la rotación interna en extensión"},"correcta":"B","exp":"El LCP es el más fuerte de los dos cruzados. Evita el desplazamiento POSTERIOR de la tibia. Se lesiona por golpe en la tibia proximal con rodilla en flexión (accidentes de coche, 'dashboard injury'). El cajón posterior lo evalúa."},
            {"id":"rod_004","concepto":"meniscos","enunciado":"¿Cuál de los dos meniscos se lesiona con mayor frecuencia?","opciones":{"A":"Menisco lateral","B":"Menisco medial","C":"Ambos por igual","D":"Depende de la edad"},"correcta":"B","exp":"El menisco medial se lesiona más (75%) porque está firmemente unido al ligamento colateral medial y la cápsula articular, lo que lo hace menos móvil. El menisco lateral es más redondo y móvil. Lesión clásica: rotación con pie fijo."},
            {"id":"rod_005","concepto":"tríada maldita","enunciado":"La 'tríada maldita' de O'Donoghue incluye lesión de:","opciones":{"A":"LCA + LCP + menisco lateral","B":"LCA + LCM + menisco medial","C":"LCP + LCL + menisco lateral","D":"LCA + LCL + menisco medial"},"correcta":"B","exp":"La tríada desgraciada (O'Donoghue): LCA + LCM + menisco medial. Ocurre por valgismo forzado con rotación. El LCM y el menisco medial están unidos, por lo que una lesión del LCM frecuentemente arrastra al menisco medial."},
            {"id":"rod_006","concepto":"ligamento colateral","enunciado":"¿Qué ligamento de la rodilla previene el valgo?","opciones":{"A":"Ligamento cruzado anterior","B":"Ligamento colateral lateral (LCL)","C":"Ligamento colateral medial (LCM)","D":"Ligamento cruzado posterior"},"correcta":"C","exp":"El LCM (medial) resiste el estrés en valgo (rodilla se abre hacia afuera). El LCL (lateral) resiste el estrés en varo (rodilla se abre hacia adentro). Lesión del LCM: dolor medial, inestabilidad valgo."},
            {"id":"rod_007","concepto":"tendón rotuliano","enunciado":"El tendón rotuliano une:","opciones":{"A":"Cuádriceps con la rótula","B":"Rótula con la tuberosidad tibial anterior","C":"Fémur con la tibia","D":"Ísquion con el fémur"},"correcta":"B","exp":"El tendón rotuliano (o ligamento rotuliano) va desde el polo inferior de la rótula hasta la tuberosidad tibial anterior. El tendón del cuádriceps va desde el cuádriceps hasta el polo superior de la rótula. Juntos forman el aparato extensor de la rodilla."},
            {"id":"rod_008","concepto":"cajón posterior","enunciado":"El signo del cajón posterior positivo indica lesión del:","opciones":{"A":"LCA","B":"LCM","C":"LCP","D":"Menisco medial"},"correcta":"C","exp":"Cajón posterior: con la rodilla a 90° de flexión, se empuja la tibia hacia atrás. Si se desplaza excesivamente hacia atrás = LCP roto. El signo del cuadro o sagging sign (la tibia 'cae' hacia atrás) también indica lesión del LCP."},
            {"id":"rod_009","concepto":"bursas rodilla","enunciado":"La bursitis más frecuente de la rodilla en trabajadores que se arrodillan es:","opciones":{"A":"Bursa semimembranosa","B":"Bursa infrarrotuliana profunda","C":"Bursa prerrotuliana","D":"Quiste de Baker"},"correcta":"C","exp":"La bursitis prerrotuliana ('rodilla del ama de casa') afecta a personas que se arrodillan mucho. Se manifiesta como una colección redondeada frente a la rótula. El quiste de Baker (poplíteo) es una bursitis posterior por derrame articular crónico."},
            {"id":"rod_010","concepto":"anatomía","enunciado":"¿Cuántos compartimentos tiene la articulación de la rodilla?","opciones":{"A":"1 (un solo compartimento)","B":"2 (medial y lateral)","C":"3 (medial, lateral y patelofemoral)","D":"4 compartimentos"},"correcta":"C","exp":"La rodilla tiene 3 compartimentos: medial (fémur medial + tibia medial), lateral (fémur lateral + tibia lateral) y patelofemoral (rótula + tróclea femoral). La artrosis puede afectar selectivamente cada compartimento."},
        ]
    },
    "huesos_craneo": {
        "nombre": "Huesos del Cráneo", "nivel": 1, "categoria": "Cráneo",
        "preguntas": [
            {"id":"hc_001","concepto":"neurocráneo","enunciado":"¿Cuántos huesos forman el neurocráneo?","opciones":{"A":"6","B":"8","C":"14","D":"22"},"correcta":"B","exp":"El neurocráneo (caja craneana) tiene 8 huesos: 1 frontal, 2 parietales, 1 occipital, 2 temporales, 1 esfenoides y 1 etmoides. El viscerocráneo (cara) tiene 14 huesos."},
            {"id":"hc_002","concepto":"neurocráneo","enunciado":"¿Cuál de estos huesos NO forma parte del neurocráneo?","opciones":{"A":"Esfenoides","B":"Etmoides","C":"Vómer","D":"Occipital"},"correcta":"C","exp":"El vómer es un hueso del viscerocráneo (forma parte del tabique nasal). Los 8 huesos del neurocráneo son: frontal, 2 parietales, occipital, 2 temporales, esfenoides y etmoides."},
            {"id":"hc_003","concepto":"silla turca","enunciado":"La silla turca, que aloja la hipófisis, se encuentra en el hueso:","opciones":{"A":"Temporal","B":"Frontal","C":"Esfenoides","D":"Etmoides"},"correcta":"C","exp":"La silla turca (fosa hipofisaria) es una depresión en el cuerpo del esfenoides. Aloja la hipófisis (glándula pituitaria). Los adenomas hipofisarios pueden comprimir el quiasma óptico superior → hemianopsia bitemporal."},
            {"id":"hc_004","concepto":"temporal","enunciado":"¿Qué estructura importante se encuentra en el hueso temporal?","opciones":{"A":"Silla turca","B":"Foramen magno","C":"Proceso mastoideo y conducto auditivo interno","D":"Crista galli"},"correcta":"C","exp":"El temporal contiene: proceso mastoideo (neumatizado), conducto auditivo externo e interno, cóclea, canales semicirculares, y aloja el oído medio. La mastoiditis es la infección de las celdillas del proceso mastoideo."},
            {"id":"hc_005","concepto":"ptérion","enunciado":"El ptérion es la unión de los huesos:","opciones":{"A":"Frontal + Occipital + Temporal","B":"Frontal + Parietal + Temporal + Esfenoides","C":"Parietal + Occipital + Temporal","D":"Frontal + Parietal + Occipital"},"correcta":"B","exp":"El ptérion es la unión en H de frontal + parietal + temporal + esfenoides en la sien. Es el punto más delgado del cráneo. Bajo el ptérion discurre la arteria meníngea media → hematoma epidural con fractura aquí."},
            {"id":"hc_006","concepto":"foramen magno","enunciado":"¿En qué hueso se encuentra el foramen magno?","opciones":{"A":"Temporal","B":"Esfenoides","C":"Parietal","D":"Occipital"},"correcta":"D","exp":"El foramen magno (agujero occipital) está en el hueso occipital. Por él pasan: el tronco del encéfalo (bulbo-médula), arterias vertebrales, arterias espinales anterior y posterior, y raíces del nervio espinal accesorio (XI)."},
            {"id":"hc_007","concepto":"sutura lambdoidea","enunciado":"La sutura lambdoidea une:","opciones":{"A":"Frontal con parietales","B":"Los dos parietales entre sí","C":"Parietales con occipital","D":"Parietales con temporales"},"correcta":"C","exp":"Suturas principales: Coronal (frontal+parietales), Sagital (entre parietales), Lambdoidea (parietales+occipital), Escamosa (temporal+parietal). Bregma = sagital+coronal. Lambda = sagital+lambdoidea."},
            {"id":"hc_008","concepto":"crista galli","enunciado":"¿En qué hueso se encuentra la crista galli?","opciones":{"A":"Frontal","B":"Etmoides","C":"Esfenoides","D":"Vómer"},"correcta":"B","exp":"La crista galli es la proyección superior del etmoides en la fosa craneal anterior. Es la inserción de la hoz del cerebro (duramadre). La lámina cribosa del etmoides, a sus lados, transmite los nervios olfativos (I par craneal)."},
            {"id":"hc_009","concepto":"techo órbita","enunciado":"¿Qué hueso forma principalmente el techo de la órbita?","opciones":{"A":"Cigomático","B":"Esfenoides","C":"Frontal","D":"Etmoides"},"correcta":"C","exp":"El techo de la órbita está formado principalmente por la porción orbitaria del frontal (y una pequeña parte del ala menor del esfenoides). El suelo de la órbita es el maxilar superior (frágil, fractura por contragolpe)."},
            {"id":"hc_010","concepto":"bregma","enunciado":"¿Cómo se denomina el punto donde se unen las suturas sagital y coronal?","opciones":{"A":"Lambda","B":"Pterion","C":"Bregma","D":"Nasion"},"correcta":"C","exp":"Bregma = unión de la sutura sagital y coronal (frontera entre frontal y parietales). En los recién nacidos, aquí se encuentra la fontanela anterior (bregmática), la más grande. Cierra a los 18-24 meses de vida."},
        ]
    },
    "craneo_foramenes": {
        "nombre": "Forámenes del Cráneo", "nivel": 1, "categoria": "Cráneo",
        "preguntas": [
            {"id":"cf_001","concepto":"nervio óptico","enunciado":"El nervio óptico (II par craneal) sale del cráneo por:","opciones":{"A":"Fisura orbitaria superior","B":"Fisura orbitaria inferior","C":"Canal óptico","D":"Foramen rotundo"},"correcta":"C","exp":"El nervio óptico (II PC) pasa por el canal óptico junto con la arteria oftálmica (rama de la carótida interna). El canal óptico está en el ala menor del esfenoides."},
            {"id":"cf_002","concepto":"fisura orbitaria","enunciado":"¿Qué nervios craneales pasan por la fisura orbitaria SUPERIOR?","opciones":{"A":"II, III, IV","B":"III, IV, V1 y VI","C":"V2, VI, VII","D":"II, VI, VII"},"correcta":"B","exp":"Fisura orbitaria superior: III (oculomotor), IV (troclear), V1 (oftálmico), VI (abducens) y la vena oftálmica superior. El síndrome de la fisura orbitaria superior paraliza todos los movimientos oculares más la sensibilidad corneal."},
            {"id":"cf_003","concepto":"foramen oval","enunciado":"Por el foramen oval sale el nervio:","opciones":{"A":"V1 (oftálmico)","B":"V2 (maxilar)","C":"V3 (mandibular)","D":"VII (facial)"},"correcta":"C","exp":"Foramen oval: V3 (nervio mandibular, rama del trigémino). Está en el ala mayor del esfenoides. Regla: V1 por fisura orbitaria superior, V2 por foramen redondo, V3 por foramen oval (creciente: de arriba a abajo)."},
            {"id":"cf_004","concepto":"foramen redondo","enunciado":"¿Qué nervio sale por el foramen redondo?","opciones":{"A":"V1","B":"V2","C":"V3","D":"IX"},"correcta":"B","exp":"El foramen redondo transmite el nervio maxilar (V2), rama del trigémino. Está en el ala mayor del esfenoides, en la fosa media. V2 pasa al canal pterigopalatino y da sensibilidad a mejilla, labio superior, encía superior."},
            {"id":"cf_005","concepto":"foramen yugular","enunciado":"Por el foramen yugular pasan los pares craneales:","opciones":{"A":"VII, VIII","B":"IX, X, XI","C":"X, XI, XII","D":"IX, X, XI y XII"},"correcta":"B","exp":"Foramen yugular: IX (glosofaríngeo), X (vago), XI (accesorio espinal) y el seno venoso sigmoideo (que se convierte en vena yugular interna). El XII sale por el canal hipogloso (diferente foramen)."},
            {"id":"cf_006","concepto":"foramen estilomastoideo","enunciado":"El nervio facial (VII par) sale del cráneo por:","opciones":{"A":"Canal auditivo interno","B":"Foramen yugular","C":"Agujero estilomastoideo","D":"Fisura petroescamosa"},"correcta":"C","exp":"El VII sale por el agujero estilomastoideo (entre apófisis estiloides y mastoides). Antes de salir, da: nervio petroso mayor (glándulas lagrimales), nervio del músculo del estribo, y cuerda del tímpano (gusto 2/3 anteriores lengua)."},
            {"id":"cf_007","concepto":"meato acústico interno","enunciado":"¿Qué nervios pasan por el meato acústico interno?","opciones":{"A":"V y VI","B":"VII y VIII","C":"IX y X","D":"Solo el VIII"},"correcta":"B","exp":"Por el meato acústico interno (en la cara posterior del peñasco del temporal) pasan: VII (facial) y VIII (vestibulococlear). Los schwannomas vestibulares (neurinomas del acústico) se localizan aquí y comprimen ambos nervios."},
            {"id":"cf_008","concepto":"foramen espinoso","enunciado":"¿Qué estructura pasa por el foramen espinoso?","opciones":{"A":"Arteria carótida interna","B":"Arteria meníngea media","C":"Nervio facial","D":"Seno cavernoso"},"correcta":"B","exp":"El foramen espinoso (ala mayor del esfenoides) transmite la arteria meníngea media, rama de la maxilar interna. Esta arteria discurre por el ptérion y puede lesionarse con fracturas temporales → hematoma epidural agudo."},
            {"id":"cf_009","concepto":"canal hipogloso","enunciado":"El nervio hipogloso (XII par) sale por:","opciones":{"A":"Foramen magno","B":"Foramen yugular","C":"Canal hipogloso","D":"Agujero estilomastoideo"},"correcta":"C","exp":"El nervio hipogloso sale por el canal hipogloso (condíleo anterior), un canal en el occipital lateral al foramen magno. Inerva todos los músculos intrínsecos y extrínsecos de la lengua (excepto el palatogloso)."},
            {"id":"cf_010","concepto":"fosas craneales","enunciado":"¿En qué fosa craneal se aloja el lóbulo frontal?","opciones":{"A":"Fosa media","B":"Fosa posterior","C":"Fosa anterior","D":"No está en ninguna fosa"},"correcta":"C","exp":"Fosa craneal anterior: lóbulos frontales. Fosa media (central): lóbulos temporales + hipófisis (silla turca). Fosa posterior: cerebelo + tronco del encéfalo. La fosa posterior está delimitada por la tienda del cerebelo (tentorio)."},
        ]
    },
    "nervios_craneales": {
        "nombre": "Nervios Craneales", "nivel": 1, "categoria": "Cráneo",
        "preguntas": [
            {"id":"nc_001","concepto":"número y nombres","enunciado":"¿Cuántos pares de nervios craneales hay?","opciones":{"A":"10","B":"11","C":"12","D":"13"},"correcta":"C","exp":"Hay 12 pares craneales (I-XII). Nemotecnia para recordarlos en orden: 'On Old Olympus Towering Tops, A Finnish Veteran's Gentle Voyage Acquires Humor' (O, O, O, T, T, A, F, V, G, V, A, H)."},
            {"id":"nc_002","concepto":"nervio vago","enunciado":"¿Cuál es el nervio craneal más largo y de mayor distribución?","opciones":{"A":"V (trigémino)","B":"VII (facial)","C":"X (vago)","D":"XI (accesorio)"},"correcta":"C","exp":"El nervio vago (X par) es el más extenso: sale del cráneo por el foramen yugular y desciende hasta el abdomen. Inerva vísceras torácicas y abdominales (parasimpático). Es el nervio del sistema nervioso autónomo por excelencia."},
            {"id":"nc_003","concepto":"músculos masticación","enunciado":"¿Qué nervio craneal inerva los músculos de la masticación?","opciones":{"A":"V1 (nervio oftálmico)","B":"V2 (nervio maxilar)","C":"V3 (nervio mandibular)","D":"VII (nervio facial)"},"correcta":"C","exp":"V3 (mandibular) es la única rama motora del trigémino. Inerva los músculos de la masticación: masetero, temporales, pterigoideos medial y lateral, más tensor del tímpano y tensor del velo del paladar."},
            {"id":"nc_004","concepto":"músculos expresión","enunciado":"Los músculos de la expresión facial están inervados por:","opciones":{"A":"Nervio trigémino (V)","B":"Nervio facial (VII)","C":"Nervio glosofaríngeo (IX)","D":"Nervio hipogloso (XII)"},"correcta":"B","exp":"El nervio facial (VII) inerva todos los músculos mímicos (expresión facial). Sus ramas periféricas: temporal, cigomática, bucal, mandibular marginal, cervical. Lesión periférica = parálisis de Bell (toda la hemicara)."},
            {"id":"nc_005","concepto":"parálisis de Bell","enunciado":"En la parálisis de Bell (parálisis facial periférica), ¿qué ocurre con la frente?","opciones":{"A":"Solo se afecta la parte inferior de la cara","B":"Se afecta toda la hemicara incluyendo la frente","C":"La frente no se afecta porque tiene inervación bilateral","D":"La frente solo se afecta en lesiones centrales"},"correcta":"B","exp":"La parálisis periférica del VII afecta TODA la hemicara (incluyendo la frente). En la parálisis central (ictus), la frente se salva porque recibe inervación bilateral cortical. Esta distinción es clave para diferenciar lesión central de periférica."},
            {"id":"nc_006","concepto":"nervio troclear","enunciado":"¿Cuál es el único nervio craneal que sale por la cara POSTERIOR del tronco del encéfalo?","opciones":{"A":"III (oculomotor)","B":"IV (troclear)","C":"VI (abducens)","D":"VII (facial)"},"correcta":"B","exp":"El nervio troclear (IV) es único porque: 1) sale por la cara posterior del mesencéfalo, 2) se decusa (cruza) antes de salir, 3) tiene el trayecto intracraneal más largo, 4) tiene el menor número de fibras de todos los PC motores."},
            {"id":"nc_007","concepto":"músculo oblicuo superior","enunciado":"El nervio troclear (IV) inerva:","opciones":{"A":"Recto superior","B":"Oblicuo inferior","C":"Oblicuo superior","D":"Recto medial"},"correcta":"C","exp":"IV = Oblicuo Superior (TROCLEAR → Trochlea → rota hacia abajo y afuera). El III inerva el resto de músculos extromotores (recto superior, inferior, medial, oblicuo inferior y elevador del párpado). El VI inerva solo el recto lateral."},
            {"id":"nc_008","concepto":"nervio abducens","enunciado":"La parálisis del nervio abducens (VI par craneal) produce:","opciones":{"A":"Ptosis palpebral y midriasis","B":"Estrabismo convergente (esotropía)","C":"Estrabismo divergente (exotropía)","D":"Diplopia vertical"},"correcta":"B","exp":"El VI inerva el recto lateral (abductor del ojo). Su parálisis → el ojo queda en aducción por el recto medial sin oposición → estrabismo convergente (esotropía). Diplopía horizontal. El VI tiene el trayecto más largo dentro del cráneo."},
            {"id":"nc_009","concepto":"nervio accesorio","enunciado":"¿Qué músculos inerva el nervio accesorio (XI par craneal)?","opciones":{"A":"Músculos de la lengua","B":"Músculos de la faringe","C":"Esternocleidomastoideo y trapecio","D":"Músculos de la laringe"},"correcta":"C","exp":"El nervio accesorio (XI) inerva el esternocleidomastoideo (rotación de la cabeza) y el trapecio (elevación del hombro). Su lesión → incapacidad de encoger el hombro y debilidad para rotar la cabeza hacia el lado opuesto."},
            {"id":"nc_010","concepto":"nervio hipogloso","enunciado":"La lesión del nervio hipogloso (XII) produce:","opciones":{"A":"Disfagia y disfonía","B":"La lengua desvía hacia el lado SANO","C":"La lengua desvía hacia el lado LESIONADO","D":"Pérdida del gusto en los 2/3 anteriores de la lengua"},"correcta":"C","exp":"La lesión del XII produce: atrofia y fasciculaciones de la lengua ipsilateral, y desviación hacia el lado LESIONADO al protruir (el lado sano empuja). La lesión de la VÍA CORTICAL (primera motoneurona) desvía la lengua hacia el lado contrario a la lesión."},
        ]
    },
    "columna": {
        "nombre": "Columna Vertebral", "nivel": 1, "categoria": "Vértebras",
        "preguntas": [
            {"id":"col_001","concepto":"número vértebras","enunciado":"¿Cuántas vértebras cervicales tiene la columna vertebral?","opciones":{"A":"5","B":"6","C":"7","D":"8"},"correcta":"C","exp":"Columna vertebral: 7 cervicales (C1-C7) + 12 torácicas (T1-T12) + 5 lumbares (L1-L5) + 5 sacras fusionadas (sacro) + 3-4 coccígeas. Total: 33-34 vértebras. Los nervios espinales son 31 pares."},
            {"id":"col_002","concepto":"curvaturas","enunciado":"¿Cuál de las siguientes curvaturas de la columna es una CIFOSIS?","opciones":{"A":"Cervical","B":"Lumbar","C":"Torácica","D":"Sacra desde el punto de vista de curvatura fisiológica principal"},"correcta":"C","exp":"Cifosis = convexidad posterior (cóncava anteriormente): torácica y sacrococcígea (son las curvaturas primarias, presentes desde el feto). Lordosis = convexidad anterior (cóncava posteriormente): cervical y lumbar (secundarias, se desarrollan al erguirse)."},
            {"id":"col_003","concepto":"curvaturas","enunciado":"¿Qué tipo de curvatura es la lordosis lumbar?","opciones":{"A":"Curvatura primaria, cóncava anteriormente","B":"Curvatura secundaria, cóncava posteriormente (convexa anteriormente)","C":"Curvatura primaria, convexa posteriormente","D":"No existe lordosis lumbar fisiológica"},"correcta":"B","exp":"La lordosis lumbar es una curvatura secundaria (se desarrolla cuando el niño comienza a caminar). Es cóncava posterior = convexa anterior. Se exagera en el embarazo. La hiperlordosis lumbar puede causar lumbalgia crónica."},
            {"id":"col_004","concepto":"médula espinal","enunciado":"¿En qué nivel termina la médula espinal en el adulto?","opciones":{"A":"T12","B":"L1-L2","C":"L3-L4","D":"S1"},"correcta":"B","exp":"La médula espinal en adultos termina entre L1 y L2 (cono medular). Por debajo continúan las raíces nerviosas formando la cola de caballo. En recién nacidos termina más abajo (L3). Por eso, la punción lumbar se hace entre L3-L4 o L4-L5."},
            {"id":"col_005","concepto":"vértebra prominente","enunciado":"¿Cuál es la vértebra prominente y cómo se identifica?","opciones":{"A":"C6, por su apófisis espinosa larga no bifurcada","B":"C7, por ser la más palpable en la nuca con apófisis espinosa larga","C":"T1, primera vértebra torácica","D":"C5, la más móvil de la columna cervical"},"correcta":"B","exp":"La vértebra prominente es C7 (vertebra prominens): tiene la apófisis espinosa más larga y es la más palpable en la nuca. C2-C6 tienen apófisis espinosas bífidas. C7 y T1 no son bífidas. Es el punto de referencia para contar las vértebras."},
            {"id":"col_006","concepto":"nervios espinales","enunciado":"¿Cuántos pares de nervios espinales hay en total?","opciones":{"A":"29","B":"31","C":"33","D":"12"},"correcta":"B","exp":"31 pares de nervios espinales: 8 cervicales (C1-C8, aunque solo hay 7 vértebras cervicales), 12 torácicos, 5 lumbares, 5 sacros y 1 coccígeo. Hay 8 pares cervicales porque C1 sale sobre C1 y C8 sale bajo C7."},
            {"id":"col_007","concepto":"cola de caballo","enunciado":"La 'cola de caballo' está formada por:","opciones":{"A":"La médula espinal lumbar y sacra","B":"Las raíces nerviosas L2-S5 que descienden en el canal raquídeo","C":"El filum terminale únicamente","D":"Los nervios simpáticos lumbares"},"correcta":"B","exp":"La cola de caballo (cauda equina) son las raíces nerviosas de L2 a S5 que descienden por el canal raquídeo tras terminar la médula (L1-L2). El síndrome de la cola de caballo: anestesia en silla de montar, disfunción esfinteriana, paraparesia."},
            {"id":"col_008","concepto":"canal medular","enunciado":"¿Qué estructura llena el canal medular por debajo del cono medular?","opciones":{"A":"La médula espinal","B":"El líquido cefalorraquídeo y las raíces nerviosas (cauda equina)","C":"La duramadre sola","D":"El filum terminale solo"},"correcta":"B","exp":"Por debajo de L1-L2: el canal raquídeo contiene LCR, la cauda equina (raíces L2-S5) y el filum terminale (L2 → cóccix). El espacio subaracnoideo lumbar es ideal para la punción lumbar (L3-L4 o L4-L5), con poco riesgo de lesionar la médula."},
            {"id":"col_009","concepto":"articulación atlantooccipital","enunciado":"La articulación atlantooccipital permite principalmente:","opciones":{"A":"Rotación de la cabeza (decir NO)","B":"Flexoextensión de la cabeza (decir SÍ)","C":"Inclinación lateral de la cabeza","D":"Todos los movimientos por igual"},"correcta":"B","exp":"La articulación atlantooccipital (C0-C1) permite flexoextensión (asentir con la cabeza = 'decir SÍ'). La atlantoaxial (C1-C2) permite la rotación (negar con la cabeza = 'decir NO'). Ambas son las más móviles de la columna cervical."},
            {"id":"col_010","concepto":"ángulo de Louis","enunciado":"El ángulo de Louis (ángulo esternal) se proyecta a nivel de:","opciones":{"A":"T2-T3","B":"T4-T5","C":"T6-T7","D":"T1-T2"},"correcta":"B","exp":"El ángulo de Louis (unión manubrioesternal) se proyecta a nivel de T4-T5, segunda articulación condroesternal, bifurcación traqueal (carina), y el inicio del arco aórtico. Es un hito anatómico clave en exploración torácica."},
        ]
    },
    "atlas_axis": {
        "nombre": "Atlas y Axis (C1-C2)", "nivel": 1, "categoria": "Vértebras",
        "preguntas": [
            {"id":"aa_001","concepto":"atlas anatomía","enunciado":"¿Qué característica anatómica distingue al atlas (C1) de todas las demás vértebras?","opciones":{"A":"Tiene apófisis espinosa muy larga","B":"No tiene cuerpo vertebral","C":"Tiene agujero transverso doble","D":"Tiene solo un pedículo"},"correcta":"B","exp":"El atlas (C1) carece de cuerpo vertebral. Tiene dos masas laterales unidas por los arcos anterior y posterior. El eje (C2) tiene la apófisis odontoides que ocupa el lugar del cuerpo del atlas (filogénicamente, la odontoides es el cuerpo del C1 que se fusionó al C2)."},
            {"id":"aa_002","concepto":"apófisis odontoides","enunciado":"La apófisis odontoides (diente) es una estructura del:","opciones":{"A":"Atlas (C1)","B":"Axis (C2)","C":"C3","D":"Occipital"},"correcta":"B","exp":"La apófisis odontoides es una proyección vertical del axis (C2) que se articula con la faceta articular del arco anterior del atlas. Funciona como pivote para la rotación de la cabeza. Su fractura es una emergencia (puede comprimir el bulbo)."},
            {"id":"aa_003","concepto":"movimientos","enunciado":"El movimiento de asentir con la cabeza ('decir SÍ') ocurre en la articulación:","opciones":{"A":"Atlantoaxial (C1-C2)","B":"Atlantooccipital (C0-C1)","C":"C2-C3","D":"Intervertebral cervical en general"},"correcta":"B","exp":"Atlantooccipital (C0-C1): flexoextensión = 'decir SÍ' (50% de la flexoextensión cervical). Atlantoaxial (C1-C2): rotación = 'decir NO' (50% de la rotación cervical). Ambas articulaciones carecen de discos intervertebrales."},
            {"id":"aa_004","concepto":"movimientos","enunciado":"El 50% de la rotación cervical total ocurre en la articulación:","opciones":{"A":"Atlantooccipital (C0-C1)","B":"Atlantoaxial (C1-C2)","C":"C2-C3","D":"C4-C5"},"correcta":"B","exp":"La articulación atlantoaxial (C1-C2) permite ~50° de rotación a cada lado (total ~100°), que es el 50% de toda la rotación cervical. Es una articulación trocoidea (en pivote). El ligamento transverso del atlas retiene la odontoides."},
            {"id":"aa_005","concepto":"ligamento transverso","enunciado":"¿Qué ligamento impide que la apófisis odontoides comprima la médula espinal?","opciones":{"A":"Ligamento longitudinal anterior","B":"Ligamento transverso del atlas","C":"Ligamento amarillo","D":"Ligamento nucal"},"correcta":"B","exp":"El ligamento transverso del atlas es el más importante de la articulación atlantoaxial. Une las dos masas laterales del atlas por detrás de la odontoides. Su rotura (trauma o artritis reumatoide) permite la subluxación anterior del atlas → riesgo de compresión medular."},
            {"id":"aa_006","concepto":"arteria vertebral","enunciado":"Las arterias vertebrales ascienden por la columna cervical pasando por:","opciones":{"A":"El canal medular","B":"Los forámenes transversos (agujeros transversos) de C1-C6","C":"Los espacios intervertebrales","D":"Los pedículos vertebrales"},"correcta":"B","exp":"Las arterias vertebrales (ramas de la subclavia) ascienden por los forámenes transversos de C6 hasta C1, luego pasan por el arco posterior del atlas y entran al cráneo por el foramen magno. Se unen para formar la arteria basilar."},
            {"id":"aa_007","concepto":"fractura odontoides","enunciado":"La fractura del tipo II de Anderson-D'Alonzo de la apófisis odontoides se localiza en:","opciones":{"A":"Punta de la odontoides","B":"Base de la odontoides (unión con el cuerpo del axis)","C":"Cuerpo del axis","D":"Arco posterior del atlas"},"correcta":"B","exp":"Fracturas de odontoides: Tipo I (punta, estable), Tipo II (base, la más frecuente y menos estable, alta tasa de pseudoartrosis), Tipo III (cuerpo del axis, buena consolidación). La Tipo II es la más importante clínicamente."},
            {"id":"aa_008","concepto":"fractura jefferson","enusiado":"La fractura de Jefferson es una fractura de:","opciones":{"A":"Apófisis odontoides del axis","B":"Arco posterior del atlas por compresión axial","C":"Masa lateral del atlas con rotura del ligamento transverso","D":"Cuerpo del C3"},"enunciado":"La fractura de Jefferson es una fractura de:","opciones":{"A":"Apófisis odontoides del axis","B":"Arco posterior del atlas por compresión axial","C":"Estallido del atlas (C1) por carga axial","D":"Cuerpo del C3"},"correcta":"C","exp":"La fractura de Jefferson es una fractura en estallido del atlas (C1) por compresión axial (carga sobre la cabeza, p.ej. zambullida). Las masas laterales se desplazan hacia afuera. En la radiografía AP transoral se ve el desplazamiento lateral bilateral de las masas del atlas."},
            {"id":"aa_009","concepto":"fractura del ahorcado","enunciado":"La fractura del ahorcado (de Hangman) afecta a:","opciones":{"A":"Cuerpo del C1","B":"Apófisis odontoides del C2","C":"Pedículos bilaterales del axis (C2)","D":"Arco anterior del C1"},"correcta":"C","exp":"La fractura del ahorcado (Hangman's fracture) es la fractura bilateral de los pedículos/istmos del axis (C2) por hiperextensión + distracción. A pesar de la inestabilidad, paradójicamente suele haber poca lesión neurológica porque el canal se amplía."},
            {"id":"aa_010","concepto":"fontanelas","enunciado":"El atlas se articula superiormente con los cóndilos del hueso:","opciones":{"A":"Parietal","B":"Temporal","C":"Esfenoides","D":"Occipital"},"correcta":"D","exp":"Las masas laterales del atlas se articulan con los cóndilos del occipital formando la articulación atlantooccipital (dos articulaciones condíleas). Esta articulación permite la flexoextensión (asentir). El foramen magno del occipital es adyacente."},
        ]
    },
    "carpo_tarso": {
        "nombre": "Carpo y Tarso", "nivel": 2, "categoria": "Miembro Superior / Inferior",
        "preguntas": [
            {"id":"ct_001","concepto":"carpo proximal","enunciado":"De radial a cubital, ¿cuál es el orden correcto de la fila proximal del carpo?","opciones":{"A":"Pisiforme - Piramidal - Semilunar - Escafoides","B":"Escafoides - Semilunar - Piramidal - Pisiforme","C":"Trapecio - Trapezoide - Grande - Ganchoso","D":"Escafoides - Piramidal - Semilunar - Pisiforme"},"correcta":"B","exp":"Fila proximal (radio→cúbito): Escafoides - Semilunar - Piramidal - Pisiforme. El pisiforme es un hueso sesamoideo incluido en el tendón del flexor cubital del carpo. Nemotecnia: 'El Señor Poco Puede'."},
            {"id":"ct_002","concepto":"carpo distal","enunciado":"¿Con qué hueso del carpo articula el primer metacarpiano (pulgar)?","opciones":{"A":"Escafoides","B":"Grande","C":"Trapecio","D":"Trapezoide"},"correcta":"C","exp":"El trapecio articula con el primer metacarpiano en la articulación carpometacarpiana del pulgar (articulación en silla de montar = sellar). Esta articulación permite los movimientos de oposición del pulgar."},
            {"id":"ct_003","concepto":"hueso fracturado","enunciado":"Tras una caída sobre la mano extendida, el paciente refiere dolor en la tabaquera anatómica. ¿Qué fractura sospechas?","opciones":{"A":"Fractura de Colles del radio","B":"Fractura del escafoides","C":"Fractura del pisiforme","D":"Fractura del ganchoso"},"correcta":"B","exp":"El dolor en la tabaquera anatómica (entre los tendones del abductor largo y extensor corto del pulgar medialmente, y el extensor largo del pulgar lateralmente) es el signo clásico de la fractura de escafoides. Puede no verse en la Rx inicial."},
            {"id":"ct_004","concepto":"tarso","enunciado":"¿Cuántos huesos forman el tarso?","opciones":{"A":"5","B":"6","C":"7","D":"8"},"correcta":"C","exp":"Tarso: 7 huesos = Calcáneo + Astrágalo + Navicular + Cuboides + 3 Cuneiformes (medial, intermedio, lateral). El calcáneo es el más grande. El astrágalo articula con la tibia."},
            {"id":"ct_005","concepto":"huesos tarso","enunciado":"¿Qué hueso del tarso se encuentra entre el astrágalo y los cuneiformes?","opciones":{"A":"Cuboides","B":"Calcáneo","C":"Navicular","D":"Cuneiforme lateral"},"correcta":"C","exp":"El navicular (escafoides del tarso) se sitúa entre el astrágalo proximalmente y los 3 cuneiformes distalmente. La enfermedad de Köhler es la necrosis avascular del navicular en niños."},
            {"id":"ct_006","concepto":"necrosis avascular","enunciado":"La necrosis avascular del escafoides carpiano se debe a:","opciones":{"A":"La infección del hueso","B":"La irrigación retrógrada del escafoides (polo proximal poco vascularizado)","C":"La inestabilidad del carpo","D":"La compresión del nervio mediano"},"correcta":"B","exp":"El escafoides tiene irrigación distal-a-proximal: los vasos entran por el polo distal y el proximal queda con circulación terminal. Una fractura en la cintura del escafoides compromete el aporte al polo proximal → necrosis avascular. Por eso las fracturas de escafoides requieren tratamiento cuidadoso."},
            {"id":"ct_007","concepto":"articulación","enunciado":"La articulación de Chopart (mediotarsiana) une:","opciones":{"A":"Calcáneo-cuboides y astrágalo-navicular","B":"Navicular y los tres cuneiformes","C":"Tarso y metatarso","D":"Tibia-peroné y astrágalo"},"correcta":"A","exp":"La articulación de Chopart (mediotarsiana) está formada por: articulación calcáneo-cuboidea + articulación astrágalonavicular. Es la línea de amputación media del pie. La articulación de Lisfranc es la tarsometatarsiana."},
        ]
    },
    "musculos_ms": {
        "nombre": "Músculos Miembro Superior", "nivel": 2, "categoria": "Miembro Superior",
        "preguntas": [
            {"id":"mms_001","concepto":"bíceps","enunciado":"El bíceps braquial realiza principalmente:","opciones":{"A":"Extensión del codo y pronación","B":"Flexión del codo y supinación del antebrazo","C":"Solo flexión del codo","D":"Abducción del hombro"},"correcta":"B","exp":"El bíceps braquial: flexión del codo (especialmente con antebrazo supinado) Y supinación del antebrazo. Es más potente como supinador que como flexor. Inervado por el nervio musculocutáneo (C5-C6)."},
            {"id":"mms_002","concepto":"tríceps","enunciado":"¿Qué músculo es el principal extensor del codo?","opciones":{"A":"Bíceps braquial","B":"Braquial anterior","C":"Tríceps braquial","D":"Braquiorradial"},"correcta":"C","exp":"El tríceps braquial (tres cabezas: larga, medial y lateral) es el principal extensor del codo. Inervado por el nervio radial. Su reflejo osteotendinoso (ROT del tríceps) evalúa C7. Se inserta en el olécranon."},
            {"id":"mms_003","concepto":"pronación","enunciado":"El músculo pronador redondo está inervado por:","opciones":{"A":"Nervio radial","B":"Nervio cubital","C":"Nervio mediano","D":"Nervio musculocutáneo"},"correcta":"C","exp":"El pronador redondo (y el pronador cuadrado) están inervados por el nervio mediano. El síndrome del pronador redondo comprime el mediano en el antebrazo proximal. El braquiorradial es un supinador superficial inervado por el radial."},
            {"id":"mms_004","concepto":"compartimentos","enunciado":"¿Qué compartimento del brazo contiene los músculos flexores?","opciones":{"A":"Posterior","B":"Lateral","C":"Anterior","D":"Medial"},"correcta":"C","exp":"El compartimento anterior del brazo contiene los flexores: bíceps braquial, braquial anterior y coracobraquial. Inervados por el musculocutáneo. El compartimento posterior contiene el tríceps (extensor), inervado por el radial."},
            {"id":"mms_005","concepto":"manguito rotador vs deltoides","enunciado":"¿Cuál es la diferencia funcional entre el deltoides y el manguito rotador?","opciones":{"A":"Ambos solo elevan el brazo","B":"Deltoides: potencia de abducción; manguito: estabilidad y rotación de la cabeza humeral","C":"Deltoides: rotación interna; manguito: rotación externa","D":"No hay diferencia funcional significativa"},"correcta":"B","exp":"El deltoides (fibras medias) es el principal motor de la abducción del hombro (15-180°). El manguito rotador estabiliza la cabeza humeral en la cavidad glenoidea (evita el ascenso) y realiza las rotaciones. Son complementarios."},
            {"id":"mms_006","concepto":"bíceps largo","enunciado":"¿Dónde se origina la cabeza LARGA del bíceps braquial?","opciones":{"A":"Apófisis coracoides de la escápula","B":"Tubérculo supraglenoideo de la escápula","C":"Cara anterior del húmero","D":"Epicóndilo lateral del húmero"},"correcta":"B","exp":"La cabeza larga del bíceps se origina en el tubérculo supraglenoideo de la escápula. Su tendón pasa por la corredera bicipital del húmero. La cabeza corta se origina en la apófisis coracoides (junto con el coracobraquial)."},
            {"id":"mms_007","concepto":"extensores muñeca","enunciado":"Los extensores del carpo/muñeca se insertan en el:","opciones":{"A":"Epicóndilo medial (epitróclea)","B":"Epicóndilo lateral","C":"Troquíter del húmero","D":"Radio distal"},"correcta":"B","exp":"Los extensores del carpo (radiales largo y corto, cubital posterior) se originan en el epicóndilo lateral. La epicondilitis lateral ('codo de tenista') es la inflamación de estas inserciones. Los FLEXORES se originan en el epicóndilo medial (epitróclea)."},
        ]
    },
    "musculos_mi": {
        "nombre": "Músculos Miembro Inferior", "nivel": 2, "categoria": "Miembro Inferior",
        "preguntas": [
            {"id":"mmi_001","concepto":"cuádriceps","enunciado":"¿Cuántas cabezas tiene el músculo cuádriceps femoral?","opciones":{"A":"2","B":"3","C":"4","D":"5"},"correcta":"C","exp":"El cuádriceps tiene 4 cabezas: recto femoral (biarticularr: también flexor de cadera), vasto medial, vasto lateral y vasto intermedio. Todas convergen en el tendón cuadricipital → rótula → tendón rotuliano → tuberosidad tibial. Extensor de la rodilla."},
            {"id":"mmi_002","concepto":"isquiotibiales","enunciado":"Los músculos isquiotibiales son:","opciones":{"A":"Cuádriceps, sartorio y grácil","B":"Bíceps femoral, semitendinoso y semimembranoso","C":"Glúteo mayor, medio y menor","D":"Aductores del muslo"},"correcta":"B","exp":"Los isquiotibiales (cara posterior del muslo): bíceps femoral (2 cabezas), semitendinoso y semimembranoso. Se originan en la tuberosidad isquiática. Función: flexión de rodilla + extensión de cadera. Inervados por el nervio ciático."},
            {"id":"mmi_003","concepto":"glúteos","enunciado":"¿Cuál es la función principal del glúteo medio?","opciones":{"A":"Extensión de la cadera","B":"Abducción de la cadera y estabilización de la pelvis","C":"Rotación externa de la cadera","D":"Flexión de la cadera"},"correcta":"B","exp":"El glúteo medio (y menor) son los principales abductores de la cadera. Estabilizan la pelvis durante la marcha (fase monopodal). Su parálisis → marcha de Trendelenburg (la pelvis cae hacia el lado contralateral al apoyar). Inervados por el nervio glúteo superior."},
            {"id":"mmi_004","concepto":"iliopsoas","enunciado":"El músculo iliopsoas está formado por:","opciones":{"A":"Ilíaco + recto femoral","B":"Ilíaco + psoas mayor","C":"Psoas mayor + psoas menor","D":"Ilíaco + pectíneo"},"correcta":"B","exp":"El iliopsoas = ilíaco (fosa ilíaca) + psoas mayor (cuerpos T12-L4). Se unen y se insertan en el trocánter menor del fémur. Es el flexor de cadera más potente. Inervado por el nervio femoral y ramas directas del plexo lumbar (L1-L4)."},
            {"id":"mmi_005","concepto":"sartorio","enunciado":"¿Cuál es el músculo más largo del cuerpo?","opciones":{"A":"Bíceps femoral","B":"Gracilis","C":"Sartorio","D":"Semitendinoso"},"correcta":"C","exp":"El sartorio es el músculo más largo del cuerpo (atraviesa dos articulaciones: cadera y rodilla). Va desde la EIAS hasta la cara medial de la tibia. Forma la 'pata de ganso' junto con el grácil y semitendinoso. Hace flexión, abducción y rotación externa de cadera + flexión de rodilla."},
            {"id":"mmi_006","concepto":"tríceps sural","enunciado":"El tendón de Aquiles es el tendón del:","opciones":{"A":"Tibial posterior","B":"Peroneo largo","C":"Tríceps sural (gemelos + sóleo)","D":"Flexor largo de los dedos"},"correcta":"C","exp":"El tendón de Aquiles = tendón del tríceps sural (gastrocnemios/gemelos + sóleo). Se inserta en el calcáneo. Es el tendón más grueso del cuerpo. Su rotura (ruido de latigazo, signo de Thompson positivo) es frecuente en deportistas mayores de 35 años."},
            {"id":"mmi_007","concepto":"marcha Trendelenburg","enunciado":"La marcha de Trendelenburg se produce por parálisis del:","opciones":{"A":"Cuádriceps","B":"Glúteo mayor","C":"Glúteo medio","D":"Iliopsoas"},"correcta":"C","exp":"La marcha de Trendelenburg: la pelvis cae hacia el lado SANO al levantar la pierna (porque el glúteo medio del lado LESIONADO no puede sostener la pelvis). El paciente inclina el tronco hacia el lado lesionado para compensar. Causas: parálisis del nervio glúteo superior, displasia de cadera, fractura de cuello femoral."},
        ]
    },
    "arterias_ms_mi": {
        "nombre": "Arterias Miembro Superior e Inferior", "nivel": 2, "categoria": "Miembro Superior / Inferior",
        "preguntas": [
            {"id":"art_001","concepto":"arteria braquial","enunciado":"¿Cómo se denomina la arteria que pasa por el canal de Hunter (aductores) en el muslo?","opciones":{"A":"Arteria ilíaca externa","B":"Arteria femoral","C":"Arteria poplítea","D":"Arteria obturatriz"},"correcta":"B","exp":"La arteria femoral (continuación de la ilíaca externa) pasa por el triángulo de Scarpa y luego por el canal de Hunter (canal de los aductores) para convertirse en arteria poplítea al atravesar el hiato del aductor mayor."},
            {"id":"art_002","concepto":"pulso radial","enunciado":"¿Dónde se toma el pulso de la arteria radial?","opciones":{"A":"En la tabaquera anatómica y en la cara volar lateral de la muñeca","B":"En el pliegue del codo","C":"En la axila","D":"En la cara medial de la muñeca"},"correcta":"A","exp":"El pulso radial se toma en la cara anterolateral de la muñeca (entre el tendón del flexor radial del carpo y el proceso estiloides del radio), o en la tabaquera anatómica. Es el lugar más común para tomar el pulso."},
            {"id":"art_003","concepto":"arteria poplítea","enunciado":"La arteria poplítea se divide en:","opciones":{"A":"Femoral superficial y profunda","B":"Tibial anterior y tronco tibioperoneal","C":"Tibial anterior y posterior directamente","D":"Peroné y tibial posterior"},"correcta":"B","exp":"La arteria poplítea se bifurca en: arteria tibial anterior (atraviesa la membrana interósea → dorso del pie → arteria dorsal del pie) y tronco tibioperoneal (que se divide en tibial posterior y arteria peroneal/fibular)."},
            {"id":"art_004","concepto":"arteria femoral","enunciado":"¿Dónde se palpa el pulso femoral?","opciones":{"A":"En el trocánter mayor","B":"En el punto medio del ligamento inguinal","C":"En la cara interna del muslo","D":"En el triángulo poplíteo"},"correcta":"B","exp":"El pulso femoral se palpa en el punto medio del ligamento inguinal (entre la EIAS y la sínfisis del pubis). El triángulo de Scarpa está delimitado por: ligamento inguinal (base), sartorio (lateral) y aductor largo (medial). Contiene: arteria + vena + nervio femoral (de lateral a medial: NAV)."},
            {"id":"art_005","concepto":"arteria axilar","enunciado":"La arteria axilar se convierte en arteria braquial a nivel de:","opciones":{"A":"Clavícula","B":"Borde inferior del músculo pectoral menor","C":"Borde inferior del músculo redondo mayor","D":"Pliegue del codo"},"correcta":"C","exp":"La arteria subclavia se convierte en axilar al pasar bajo la clavícula. La arteria axilar se convierte en braquial al cruzar el borde inferior del músculo redondo mayor (teres major). La braquial se divide en radial y cubital a nivel del pliegue del codo."},
            {"id":"art_006","concepto":"isquemia","enunciado":"En oclusión aguda de arteria periférica, ¿cuáles son las '6 P' de la isquemia?","opciones":{"A":"Palidez, pulso, presión, parestesias, paresia, profundidad","B":"Pain (dolor), Pallor (palidez), Pulselessness, Paresthesia, Paralysis, Poikilothermia","C":"Presión, Palidez, Parestesias, Paresia, Palpación, Presión","D":"Pulso, Palidez, Purpura, Paresis, Pain, Profundidad"},"correcta":"B","exp":"Las 6P de la isquemia aguda de extremidad: Pain (dolor), Pallor (palidez), Pulselessness (ausencia de pulso), Paresthesia (parestesias), Paralysis (parálisis), Poikilothermia (frialdad). La parálisis y anestesia indican isquemia grave con lesión nerviosa inminente."},
            {"id":"art_007","concepto":"arteria tibial posterior","enunciado":"¿Dónde se palpa el pulso de la arteria tibial posterior?","opciones":{"A":"Cara anterior del tobillo","B":"Dorso del pie entre 1er y 2er metatarsianos","C":"Cara posterior del maléolo medial","D":"Espacio poplíteo"},"correcta":"C","exp":"La arteria tibial posterior se palpa en la cara posterior del maléolo medial (entre el maléolo y el tendón de Aquiles). La arteria dorsal del pie (tibial anterior) se palpa en el dorso del pie entre los tendones del 1er y 2do dedo."},
        ]
    },
    "articulacion_hombro": {
        "nombre": "Articulación del Hombro", "nivel": 2, "categoria": "Miembro Superior",
        "preguntas": [
            {"id":"ah_001","concepto":"tipo articulación","enunciado":"La articulación glenohumeral es de tipo:","opciones":{"A":"Condílea (elipsoidea)","B":"Enartrosis (esférica o cotiloidea)","C":"Troclear","D":"Artrodia (plana)"},"correcta":"B","exp":"La glenohumeral es una enartrosis (articulación esférica): 3 ejes, 3 planos, máxima movilidad pero mínima estabilidad ósea. Por eso es la articulación que más se luxa. La estabilidad depende de: cápsula, labrum glenoideo, ligamentos glenohumerales y manguito rotador."},
            {"id":"ah_002","concepto":"labrum","enunciado":"¿Cuál es la función del labrum glenoideo?","opciones":{"A":"Separar la articulación en dos cámaras","B":"Profundizar la cavidad glenoidea y aumentar la estabilidad","C":"Lubricar la articulación","D":"Transmitir cargas axiales"},"correcta":"B","exp":"El labrum glenoideo es un rodete fibrocartilaginoso que rodea la cavidad glenoidea, profundizándola (de plana a cóncava). Aumenta la superficie de contacto un 70%. La lesión de Bankart = arrancamiento del labrum anteroinferior en luxaciones anteriores."},
            {"id":"ah_003","concepto":"luxación hombro","enunciado":"¿Cuál es la dirección más frecuente de la luxación de hombro?","opciones":{"A":"Posterior","B":"Inferior (luxatio erecta)","C":"Anterior","D":"Superior"},"correcta":"C","exp":"El 95% de las luxaciones de hombro son anteriores (subcoracoidea). La cabeza humeral queda anterior al glenoide. Mecanismo: caída con el brazo en abducción y rotación externa. Riesgo de lesión del nervio axilar y arteria axilar."},
            {"id":"ah_004","concepto":"acromioclavicular","enunciado":"La articulación acromioclavicular es de tipo:","opciones":{"A":"Enartrosis","B":"Artrodia (plana)","C":"Troclear","D":"En silla de montar"},"correcta":"B","exp":"La articulación acromioclavicular (AC) es una artrodia (articulación plana): permite deslizamiento en todos los planos pero con movilidad limitada. Se lesiona en caídas sobre el hombro (separación AC). El ligamento coracoclavicular estabiliza la articulación."},
            {"id":"ah_005","concepto":"nervio axilar","enunciado":"¿Qué músculo inerva el nervio axilar?","opciones":{"A":"Supraespinoso e infraespinoso","B":"Deltoides y teres minor","C":"Subescapular y teres major","D":"Bíceps y coracobraquial"},"correcta":"B","exp":"El nervio axilar (C5-C6, del fascículo posterior) inerva el deltoides y el teres minor (parte del manguito rotador). Rodea el cuello quirúrgico del húmero → riesgo de lesión en fracturas del cuello humeral o luxaciones anteriores de hombro."},
            {"id":"ah_006","concepto":"bursa subacromial","enunciado":"La bursitis más frecuente del hombro afecta a la bursa:","opciones":{"A":"Subcoracoidea","B":"Subdeltoidea / subacromial","C":"Bicipitorradial","D":"Escapulocostal"},"correcta":"B","exp":"La bursa subacromial-subdeltoidea es la más grande del cuerpo y la más frecuentemente afectada en el hombro. Se inflama en el síndrome de atrapamiento subacromial (junto con el tendón del supraespinoso). Dolor a la abducción de 60-120°."},
            {"id":"ah_007","concepto":"arco de movimiento","enunciado":"El rango normal de abducción del hombro es aproximadamente:","opciones":{"A":"90°","B":"120°","C":"160-180°","D":"270°"},"correcta":"C","exp":"Abducción del hombro: 0-180°. De 0-15° = supraespinoso. De 15-90° = deltoides (glenohumeral). De 90-180° = escápula rota (ritmo escapulohumeral 2:1). Sin rotación escapular, la abducción quedaría bloqueada a 90° por el troquíter contra el acromion."},
        ]
    },
    "ligamentos_columna": {
        "nombre": "Ligamentos de la Columna", "nivel": 2, "categoria": "Vértebras",
        "preguntas": [
            {"id":"lc_001","concepto":"LLA","enunciado":"¿Qué movimiento de la columna previene el ligamento longitudinal ANTERIOR (LLA)?","opciones":{"A":"La hiperflexión","B":"La hiperextensión","C":"La rotación excesiva","D":"La lateralización"},"correcta":"B","exp":"El LLA (ligamento longitudinal anterior) va por la cara anterior de los cuerpos vertebrales. Previene la hiperextensión de la columna. Es el ligamento más resistente de la columna. Se tensa en extensión."},
            {"id":"lc_002","concepto":"LLP","enunciado":"El ligamento longitudinal POSTERIOR (LLP) se localiza en:","opciones":{"A":"Cara anterior de los cuerpos vertebrales","B":"Cara posterior de los cuerpos vertebrales (dentro del canal raquídeo)","C":"Entre las láminas vertebrales","D":"Entre las apófisis espinosas"},"correcta":"B","exp":"El LLP va por la cara posterior de los cuerpos vertebrales, dentro del canal raquídeo. Previene la hiperflexión y contiene el núcleo pulposo. Es más débil en su parte posterolateral → las hernias discales suelen ser posterolaterales."},
            {"id":"lc_003","concepto":"ligamento amarillo","enunciado":"¿Qué tipo de fibras predomina en el ligamento amarillo (flavum)?","opciones":{"A":"Fibras de colágeno tipo I","B":"Fibras elásticas (elastina)","C":"Fibras de colágeno tipo II","D":"Fibrocartílago"},"correcta":"B","exp":"El ligamento flavum (amarillo) contiene 80% de fibras elásticas → le da su color amarillo. Une las láminas de vértebras adyacentes. Su hipertrofia (estenosis de canal) es causa frecuente de estenosis espinal lumbar en mayores. Se tensa en flexión."},
            {"id":"lc_004","concepto":"ligamento flavum","enunciado":"¿Qué ligamento se perfora en la punción lumbar/epidural?","opciones":{"A":"Ligamento supraespinoso","B":"Ligamento interespinoso","C":"Ligamento longitudinal posterior","D":"Ligamento flavum (amarillo)"},"correcta":"D","exp":"En la punción epidural lumbar, la aguja perfora: piel → tejido subcutáneo → ligamento supraespinoso → ligamento interespinoso → ligamento flavum → espacio epidural. La sensación de 'pérdida de resistencia' al atravesar el flavum confirma la entrada al espacio epidural."},
            {"id":"lc_005","concepto":"ligamento nucal","enunciado":"¿Cómo se denomina el ligamento supraespinoso en la región cervical?","opciones":{"A":"Ligamento flavum cervical","B":"Ligamento nucal (nuca)","C":"Ligamento transverso del atlas","D":"Membrana atlantooccipital"},"correcta":"B","exp":"El ligamento nucal es la extensión cervical del ligamento supraespinoso, pero es mucho más grueso y fibroso. Va desde la protuberancia occipital externa hasta C7. En cuadrúpedos es muy desarrollado para soportar el peso de la cabeza."},
            {"id":"lc_006","concepto":"inestabilidad columna","enunciado":"¿Cuántos 'pilares' de la columna pueden lesionarse antes de que sea inestable (concepto de Denis)?","opciones":{"A":"Si se lesiona 1 pilar","B":"Si se lesionan 2 o 3 pilares","C":"Solo si se lesionan los 3 pilares","D":"La inestabilidad no depende del número de pilares"},"correcta":"B","exp":"Denis divide la columna en 3 columnas: anterior (LLA + mitad anterior del disco y cuerpo), media (mitad posterior del cuerpo + LLP), posterior (arcos posteriores + ligamentos posteriores). Si se lesionan 2 o más columnas → inestabilidad. La columna media es la clave."},
            {"id":"lc_007","concepto":"discectomía","enunciado":"¿Qué ligamento actúa como barrera natural conteniendo el núcleo pulposo?","opciones":{"A":"Ligamento longitudinal anterior","B":"Ligamento transverso","C":"Anillo fibroso del disco","D":"Ligamento interespinoso"},"correcta":"C","exp":"El anillo fibroso (fibras de colágeno oblicuas en capas concéntricas) es la barrera que contiene el núcleo pulposo. Cuando el anillo se rompe, el núcleo pulposo se hernia → compresión de raíces nerviosas. La hernia posterolateral es la más frecuente porque el anillo es más débil aquí y el LLP no llega."},
        ]
    },
    "articulacion_codo": {
        "nombre": "Articulación del Codo", "nivel": 3, "categoria": "Miembro Superior",
        "preguntas": [
            {"id":"ac_001","concepto":"anatomía codo","enunciado":"¿Cuántos huesos participan en la articulación del codo?","opciones":{"A":"2 (húmero y radio)","B":"2 (húmero y cúbito)","C":"3 (húmero, radio y cúbito)","D":"4 huesos"},"correcta":"C","exp":"La articulación del codo está formada por 3 huesos: húmero + radio + cúbito. Comprende 3 articulaciones en una cápsula: humerocubital (troclear, flexoextensión), humeroradial (condílea) y radiocubital proximal (trocoidea, pronosupinación)."},
            {"id":"ac_002","concepto":"nervio cubital","enunciado":"¿Por qué zona pasa el nervio cubital a nivel del codo?","opciones":{"A":"Por delante del epicóndilo medial","B":"Por el surco del nervio cubital (epitrócleo-olecraniano)","C":"Por el canal carpiano","D":"Por la fosa antecubital"},"correcta":"B","exp":"El nervio cubital (ulnar) pasa por el surco del nervio cubital, entre el epicóndilo medial (epitróclea) y el olécranon. Es muy superficial aquí → vulnerable. Al golpearse el 'hueso de la alegría' (nervio cubital), se siente el hormigueo en 4º-5º dedos."},
            {"id":"ac_003","concepto":"epicondilitis","enunciado":"La epicondilitis LATERAL ('codo de tenista') afecta a los tendones de los:","opciones":{"A":"Flexores del carpo (epitróclea)","B":"Extensores del carpo (epicóndilo lateral)","C":"Pronadores del antebrazo","D":"Flexores de los dedos"},"correcta":"B","exp":"Epicondilitis lateral (codo de tenista): inflamación crónica en el origen de los extensores del carpo en el epicóndilo lateral. Dolor al extender la muñeca contra resistencia. La EPITROCLEITIS (codo de golfista) afecta los flexores en el epicóndilo medial."},
            {"id":"ac_004","concepto":"fosa cubital","enunciado":"La fosa antecubital (cubital anterior) contiene de lateral a medial:","opciones":{"A":"Nervio mediano, arteria braquial, tendón del bíceps","B":"Tendón del bíceps, arteria braquial, nervio mediano","C":"Arteria radial, vena mediana, nervio cubital","D":"Nervio radial, arteria braquial, nervio mediano"},"correcta":"B","exp":"La fosa antecubital (fosa del codo) contiene de lateral a medial: Tendón del bíceps - Arteria braquial (con sus venas) - Nervio mediano. El nervio radial no está en la fosa propiamente dicha (pasa lateral). Nemotecnia: BAN (Bíceps-Arteria-Nervio)."},
            {"id":"ac_005","concepto":"luxación codo","enunciado":"La luxación del codo más frecuente es hacia:","opciones":{"A":"Anterior","B":"Medial","C":"Posterior","D":"Lateral"},"correcta":"C","exp":"La luxación posterior del codo es la más frecuente (90%). Ocurre por caída sobre la mano extendida con el codo en extensión. El radio y el cúbito se desplazan posteriormente al húmero. En niños, la 'cabeza radial subluxada' (nursemaid's elbow) es la lesión más frecuente del codo."},
        ]
    },
    "disco_intervertebral": {
        "nombre": "Disco Intervertebral", "nivel": 3, "categoria": "Vértebras",
        "preguntas": [
            {"id":"di_001","concepto":"estructura disco","enunciado":"¿Cuáles son las dos partes del disco intervertebral?","opciones":{"A":"Cartílago hialino y fibrocartílago","B":"Núcleo pulposo y anillo fibroso","C":"Ligamento y cartílago","D":"Hueso esponjoso y cortical"},"correcta":"B","exp":"El disco intervertebral tiene: Anillo fibroso (capas concéntricas de fibras de colágeno oblicuas, más grueso anterior y lateralmente) + Núcleo pulposo (gel hidrofílico de proteoglicanos, remanente de la notocorda, hidratado al 80%)."},
            {"id":"di_002","concepto":"hernia discal","enunciado":"¿Cuál es el nivel más frecuente de hernia discal lumbar?","opciones":{"A":"L1-L2","B":"L2-L3","C":"L3-L4","D":"L4-L5 y L5-S1"},"correcta":"D","exp":"El 95% de las hernias lumbares ocurren en L4-L5 y L5-S1. La hernia L4-L5 comprime la raíz L5 (pie caído, extensión del 1er dedo). La hernia L5-S1 comprime S1 (pérdida del reflejo aquíleo, debilidad de la flexión plantar)."},
            {"id":"di_003","concepto":"notocorda","enunciado":"El núcleo pulposo es un remanente de:","opciones":{"A":"El periostio embrionario","B":"La notocorda","C":"El mesodermo paraxial","D":"El ectodermo"},"correcta":"B","exp":"El núcleo pulposo es un remanente de la notocorda (estructura embrionaria que induce la formación del sistema nervioso central). Es un gel altamente hidrofílico que actúa como amortiguador de impactos. Se deshidrata con la edad (reducción de altura discal)."},
            {"id":"di_004","concepto":"dirección hernia","enunciado":"¿Por qué la mayoría de las hernias discales son posterolaterales?","opciones":{"A":"Por la forma de los músculos paravertebrales","B":"Porque el anillo fibroso es más débil posterolateralmente y el LLP no cubre esa zona","C":"Porque el LLA es muy grueso y refuerza la parte anterior","D":"Por el movimiento predominante de rotación"},"correcta":"B","exp":"Las hernias discales son posterolaterales porque: 1) el anillo fibroso tiene fibras más escasas en su parte posterolateral, 2) el ligamento longitudinal posterior (LLP) es más estrecho y no cubre esa zona. Por eso comprimen la raíz nerviosa del nivel inferior (la que ya ha salido por el foramen)."},
            {"id":"di_005","concepto":"síndrome cauda equina","enunciado":"Una hernia discal masiva central que comprime la cauda equina produce:","opciones":{"A":"Monoparesia de un miembro","B":"Anestesia en silla de montar + disfunción esfinteriana","C":"Solo dolor lumbar sin déficit neurológico","D":"Parálisis de los cuádriceps bilateralmente"},"correcta":"B","exp":"El síndrome de la cauda equina es una URGENCIA QUIRÚRGICA: hernia discal central masiva que comprime todas las raíces L2-S5. Produce: anestesia perineal en 'silla de montar', incontinencia/retención urinaria y fecal, paresia de extremidades. Requiere descompresión urgente (<24h)."},
        ]
    },
    "suturas_fosas": {
        "nombre": "Suturas y Fosas Craneales", "nivel": 3, "categoria": "Cráneo",
        "preguntas": [
            {"id":"sf_001","concepto":"suturas","enunciado":"¿Qué sutura une los dos huesos parietales?","opciones":{"A":"Sutura coronal","B":"Sutura sagital","C":"Sutura lambdoidea","D":"Sutura escamosa"},"correcta":"B","exp":"Sutura sagital: une los dos parietales (en la línea media del cráneo). Sutura coronal: frontal + parietales. Sutura lambdoidea: parietales + occipital. Sutura escamosa: parietal + temporal."},
            {"id":"sf_002","concepto":"fontanelas","enunciado":"La fontanela anterior (bregmática) cierra normalmente a los:","opciones":{"A":"3-6 meses","B":"6-12 meses","C":"18-24 meses","D":"3-4 años"},"correcta":"C","exp":"La fontanela anterior (bregmática, en el bregma = unión sagital+coronal) es la mayor. Cierra entre 18-24 meses. La fontanela posterior (lambda) cierra a los 2-3 meses. La fontanela tensa y abombada en un lactante sugiere hipertensión intracraneal."},
            {"id":"sf_003","concepto":"fosas craneales","enunciado":"¿Qué estructura forma el suelo de la fosa craneal POSTERIOR?","opciones":{"A":"Ala mayor del esfenoides","B":"Porción orbitaria del frontal","C":"Porción petrosa del temporal y occipital","D":"Cuerpo del esfenoides"},"correcta":"C","exp":"Fosa posterior: formada por la porción petrosa del temporal + occipital. Aloja cerebelo, puente y bulbo raquídeo. Es la más profunda y pequeña. Delimitada anteriormente por el dorso de la silla turca; cubierta por el tentorio del cerebelo."},
            {"id":"sf_004","concepto":"craneostosis","enunciado":"El cierre prematuro de la sutura sagital (escafocefalia) produce:","opciones":{"A":"Cráneo corto y ancho","B":"Cráneo largo y estrecho (dolicocéfalo)","C":"Asimetría craneal (plagiocefalia)","D":"Cráneo en torre (turricefalia)"},"correcta":"B","exp":"Craneosinostosis sagital (más frecuente): el cráneo crece en dirección anteroposterior compensatoriamente → dolicocefalia (cráneo largo y estrecho). Si se cierra la sutura coronal: braquicefalia (corto y ancho). Si es unilateral: plagiocefalia."},
            {"id":"sf_005","concepto":"hematoma epidural","enunciado":"El hematoma epidural clásico produce un intervalo lúcido porque:","opciones":{"A":"El sangrado es venoso y lento","B":"El sangrado arterial (meníngea media) forma un hematoma que inicialmente no comprime la corteza","C":"La lesión es infratentorial","D":"El hematoma es crónico"},"correcta":"B","exp":"Hematoma epidural: hemorragia arterial (arteria meníngea media, tras fractura del ptérion) entre el cráneo y la duramadre. Clásico: TCE → pérdida de consciencia breve → intervalo lúcido (horas) → deterioro neurológico rápido por efecto de masa. Es una urgencia neuroquirúrgica."},
        ]
    },
}

NIVELES = {
    1: list(k for k, v in BANCO.items() if v["nivel"] == 1),
    2: list(k for k, v in BANCO.items() if v["nivel"] == 2),
    3: list(k for k, v in BANCO.items() if v["nivel"] == 3),
}

CATEGORIAS = {
    "Miembro Superior": [k for k, v in BANCO.items() if v["categoria"] in ("Miembro Superior", "Miembro Superior / Inferior")],
    "Miembro Inferior": [k for k, v in BANCO.items() if v["categoria"] in ("Miembro Inferior", "Miembro Superior / Inferior")],
    "Cráneo": [k for k, v in BANCO.items() if v["categoria"] == "Cráneo"],
    "Vértebras": [k for k, v in BANCO.items() if v["categoria"] == "Vértebras"],
}
